steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image build add commit id tag'
    args: ['build', '-f', './environment/production/Dockerfile', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image build add latest tag'
    args: ['build', '-f', './environment/production/Dockerfile', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image push add commit id tag'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image push add latest tag'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:latest']
  - name: 'google/cloud-sdk'
    id: 'instance deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh waiwaichan-server --zone=asia-northeast1-a --command="
          sudo su && \
          cd /app/waiwaichan && \
          git config --global --add safe.directory /app/waiwaichan && \
          git pull origin main && \
          docker compose -f ./environment/production/docker-compose.yml down && \
          docker container prune -f && \
          docker image prune -f && \
          docker volume prune -f && \
          docker system prune -f && \
          cat config/key.json | docker login -u _json_key --password-stdin asia-northeast1-docker.pkg.dev && \
          docker compose -f ./environment/production/docker-compose.yml pull && \
          docker compose -f ./environment/production/docker-compose.yml up -d
        "
