steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/image:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'image',
           '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/image:$COMMIT_SHA',
           '--region', 'us-central1',
           '--platform', 'managed']
images:
  - 'gcr.io/$PROJECT_ID/image:$COMMIT_SHA'
