steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', './environment/production/Dockerfile', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA']
  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh waiwaichan-server --zone=asia-northeast1-a --command="
          cd /app/waiwaichan && \
          sudo docker compose -f ./environment/production/docker-compose.yml down && \
          git pull origin main && \
          sudo docker compose -f ./environment/production/docker-compose.yml up -d
        "
