steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image build add commit id tag'
    args: ['build', '-f', './environment/production/Dockerfile', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image build add latest tag'
    args: ['build', '-f', './environment/production/Dockerfile', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image push add commit id tag'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image push add latest tag'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:latest']
  - name: 'google/cloud-sdk'
    id: 'instance deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh waiwaichan-server --zone=asia-northeast1-a --command="
          cd /app/waiwaichan && \
          sudo docker compose -f ./environment/production/docker-compose.yml down && \
          git config --global --add safe.directory /app/waiwaichan && \
          sudo git pull origin main && \
          sudo docker rm $(docker ps -aq) && \
          sudo docker rmi $(docker images -q) && \
          gcloud auth activate-service-account --key-file=config/key.json && \
          cat config/key.json | docker login -u _json_key --password-stdin asia-northeast1-docker.pkg.dev && \
          sudo docker pull asia-northeast1-docker.pkg.dev/waiwai-406106/waiwaichan/image:latest && \
          sudo docker compose -f ./environment/production/docker-compose.yml up -d
        "
