steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', '/environment/production/Dockerfile', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '-f', '/environment/production/Dockerfile', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/waiwaichan/image:$SHORT_SHA']
  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh waiwaichan-server --zone=asia-northeast1-a --command="
          cd waiwaichan/environment/production && \
          sudo docker compose down && \
          git pull origin main && \
          sudo docker compose up -d
        "

