services:
  backend:
    container_name: waiwai-backend
    restart: always
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-net
  migrate:
    container_name: waiwai-migrate
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-net
    command: ["npm", "run", "migrate"]
  database:
    container_name: waiwai-database
    env_file:
      - .env
    restart: always
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db-net
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
networks:
  db-net:
    driver: bridge
volumes:
  mysql_data:
