services:
  backend:
    container_name: waiwai-backend
    restart: always
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: backend_node_modules
        target: /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-net
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: config/key.json
    command: sh -c "npm run dev"
  scheduler:
    container_name: waiwai-scheduler
    restart: "always"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: scheduler_node_modules
        target: /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-net
    command: sh -c "npm i && npm run dev:scheduler"
  migrate:
    container_name: waiwai-migrate
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: migrate_node_modules
        target: /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-net
    command: sh -c "npm i && npm run migrate && npm run seed"
  database:
    container_name: waiwai-database
    env_file:
      - .env
    restart: always
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db-net
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
networks:
  db-net:
    driver: bridge
volumes:
  mysql_data:
  backend_node_modules:
  scheduler_node_modules:
  migrate_node_modules:
