export const RepoTypes = {
	Mutex: Symbol.for("Mutex"),
	DatabaseConnector: Symbol.for("DatabaseConnector"),
	Transaction: Symbol.for("Transaction"),
	CandyRepository: Symbol.for("CandyRepository"),
	CrownRepository: Symbol.for("CrownRepository"),
	CandyItemRepository: Symbol.for("CandyItemRepository"),
	UserCandyItemRepository: Symbol.for("UserCandyItemRepository"),
	ReminderRepository: Symbol.for("ReminderRepository"),
	ThreadRepository: Symbol.for("ThreadRepository"),
	PersonalityRepository: Symbol.for("PersonalityRepository"),
	ContextRepository: Symbol.for("ContextRepository"),
	PersonalityContextRepository: Symbol.for("PersonalityContextRepository"),
	ChatAIRepository: Symbol.for("ChatAIRepository"),
	TranslateRepository: Symbol.for("TranslateRepository"),
	PullRequestRepository: Symbol.for("PullRequestRepository"),
	StickyRepository: Symbol.for("StickyRepository"),
	CommunityRepository: Symbol.for("CommunityRepository"),
	UserRepository: Symbol.for("UserRepository"),
	ChannelRepository: Symbol.for("ChannelRepository"),
	RoleRepository: Symbol.for("RoleRepository"),
	MessageRepository: Symbol.for("MessageRepository"),
	DataDeletionCircular: Symbol.for("DataDeletionCircular"),
	RoomAddChannelRepository: Symbol.for("RoomAddChannelRepository"),
	RoomNotificationChannelRepository: Symbol.for(
		"RoomNotificationChannelRepository",
	),
	CandyNotificationChannelRepository: Symbol.for(
		"CandyNotificationChannelRepository",
	),
	CrownNotificationChannelRepository: Symbol.for(
		"CrownNotificationChannelRepository",
	),
	RoomChannelRepository: Symbol.for("RoomChannelRepository"),
	RoomCategoryChannelRepository: Symbol.for("RoomCategoryChannelRepository"),
	RolePredefinedRoleRepository: Symbol.for("RolePredefinedRoleRepository"),
	PredefinedRoleRepository: Symbol.for("PredefinedRoleRepository"),
	PredefinedRoleCommandRepository: Symbol.for(
		"PredefinedRoleCommandRepository",
	),
	SequelizeModels: Symbol.for("SequelizeModels"),
	Logger: Symbol.for("Logger"),
};
export const LogicTypes = {
	ThreadLogic: Symbol.for("ThreadLogic"),
	PersonalityLogic: Symbol.for("PersonalityLogic"),
	ContextLogic: Symbol.for("ContextLogic"),
	PersonalityContextLogic: Symbol.for("PersonalityContextLogic"),
	ChatAILogic: Symbol.for("ChatAILogic"),
	CandyLogic: Symbol.for("CandyLogic"),
	ReminderLogic: Symbol.for("ReminderLogic"),
	PullRequestLogic: Symbol.for("PullRequestLogic"),
	TranslatorLogic: Symbol.for("TranslateLogic"),
	DiceLogic: Symbol.for("DiceLogic"),
	StickyLogic: Symbol.for("StickyLogic"),
	UtilityLogic: Symbol.for("UtilityLogic"),
	CommunityLogic: Symbol.for("CommunityLogic"),
	UserLogic: Symbol.for("UserLogic"),
	ChannelLogic: Symbol.for("ChannelLogic"),
	RoleLogic: Symbol.for("RoleLogic"),
	MessageLogic: Symbol.for("MessageLogic"),
	CrownLogic: Symbol.for("CrownLogic"),
	dataDeletionCircularLogic: Symbol.for("dataDeletionCircularLogic"),
	RoomAddChannelLogic: Symbol.for("RoomAddChannelLogic"),
	RoomNotificationChannelLogic: Symbol.for("RoomNotificationChannelLogic"),
	CandyNotificationChannelLogic: Symbol.for("CandyNotificationChannelLogic"),
	CrownNotificationChannelLogic: Symbol.for("CrownNotificationChannelLogic"),
	RoomChannelLogic: Symbol.for("RoomChannelLogic"),
	RoomCategoryChannelLogic: Symbol.for("RoomCategoryChannelLogic"),
	PredefinedRoleLogic: Symbol.for("PredefinedRoleLogic"),
};

export const RouteTypes = {
	SlashCommandRoute: Symbol.for("SlashCommandRoute"),
	MessageReplyRoute: Symbol.for("MessageReplyRoute"),
	ReadyStateRoute: Symbol.for("ReadyStateRoute"),
	ReactionRoute: Symbol.for("ReactionRoute"),
	BotAddRoute: Symbol.for("BotAddRoute"),
	BotRemoveRoute: Symbol.for("BotRemoveRoute"),
	UserAddRoute: Symbol.for("UserAddRoute"),
	UserRemoveRoute: Symbol.for("UserRemoveRoute"),
	MessageDeleteRoute: Symbol.for("MessageDeleteRoute"),
	ChannelCreateRoute: Symbol.for("ChannelCreateRoute"),
	ChannelDeleteRoute: Symbol.for("ChannelDeleteRoute"),
	RoleCreateRoute: Symbol.for("RoleCreateRoute"),
	RoleDeleteRoute: Symbol.for("RoleDeleteRoute"),
	VoiceChannelEventRoute: Symbol.for("VoiceChannelEventRoute"),
};

export const SchedulerRepoTypes = {
	ReminderSchedulerRepository: Symbol.for("ReminderSchedulerRepository"),
};

export const HandlerTypes = {
	SlashCommandHandler: Symbol.for("SlashCommandHandler"),
	CommandPermissionChecker: Symbol.for("CommandPermissionChecker"),
	ReactionHandler: Symbol.for("ReactionHandler"),
	MessageHandler: Symbol.for("MessageHandler"),
	BotAddHandler: Symbol.for("BotAddHandler"),
	BotRemoveHandler: Symbol.for("BotRemoveHandler"),
	UserAddHandler: Symbol.for("UserAddHandler"),
	UserRemoveHandler: Symbol.for("UserRemoveHandler"),
	MessageDeleteHandler: Symbol.for("MessageDeleteHandler"),
	ChannelCreateHandler: Symbol.for("ChannelCreateHandler"),
	ChannelDeleteHandler: Symbol.for("ChannelDeleteHandler"),
	RoleCreateHandler: Symbol.for("RoleCreateHandler"),
	RoleDeleteHandler: Symbol.for("RoleDeleteHandler"),
	VoiceChannelEventHandler: Symbol.for("VoiceChannelEventHandler"),
};
