export const RepoTypes = {
	Mutex: Symbol.for("Mutex"),
	DatabaseConnector: Symbol.for("DatabaseConnector"),
	Transaction: Symbol.for("Transaction"),
	CandyRepository: Symbol.for("CandyRepository"),
	CrownRepository: Symbol.for("CrownRepository"),
	CandyItemRepository: Symbol.for("CandyItemRepository"),
	UserCandyItemRepository: Symbol.for("UserCandyItemRepository"),
	ReminderRepository: Symbol.for("ReminderRepository"),
	ThreadRepository: Symbol.for("ThreadRepository"),
	PersonalityRepository: Symbol.for("PersonalityRepository"),
	ContextRepository: Symbol.for("ContextRepository"),
	PersonalityContextRepository: Symbol.for("PersonalityContextRepository"),
	ChatAIRepository: Symbol.for("ChatAIRepository"),
	TranslateRepository: Symbol.for("TranslateRepository"),
	PullRequestRepository: Symbol.for("PullRequestRepository"),
	StickyRepository: Symbol.for("StickyRepository"),
	CommunityRepository: Symbol.for("CommunityRepository"),
	UserRepository: Symbol.for("UserRepository"),
	ChannelRepository: Symbol.for("ChannelRepository"),
	DataDeletionCircular: Symbol.for("DataDeletionCircular"),
	RoomAddChannelRepository: Symbol.for("RoomAddChannelRepository"),
	RoomNotificationChannelRepository: Symbol.for(
		"RoomNotificationChannelRepository",
	),
	RoomChannelRepository: Symbol.for("RoomChannelRepository"),
	RoomCategoryChannelRepository: Symbol.for("RoomCategoryChannelRepository"),
	SequelizeModels: Symbol.for("SequelizeModels"),
	Logger: Symbol.for("Logger"),
};
export const LogicTypes = {
	ThreadLogic: Symbol.for("ThreadLogic"),
	PersonalityLogic: Symbol.for("PersonalityLogic"),
	ContextLogic: Symbol.for("ContextLogic"),
	PersonalityContextLogic: Symbol.for("PersonalityContextLogic"),
	ChatAILogic: Symbol.for("ChatAILogic"),
	CandyLogic: Symbol.for("CandyLogic"),
	ReminderLogic: Symbol.for("ReminderLogic"),
	PullRequestLogic: Symbol.for("PullRequestLogic"),
	TranslatorLogic: Symbol.for("TranslateLogic"),
	DiceLogic: Symbol.for("DiceLogic"),
	StickyLogic: Symbol.for("StickyLogic"),
	UtilityLogic: Symbol.for("UtilityLogic"),
	CommunityLogic: Symbol.for("CommunityLogic"),
	UserLogic: Symbol.for("UserLogic"),
	ChannelLogic: Symbol.for("ChannelLogic"),
	CrownLogic: Symbol.for("CrownLogic"),
	dataDeletionCircularLogic: Symbol.for("dataDeletionCircularLogic"),
	RoomAddChannelLogic: Symbol.for("RoomAddChannelLogic"),
	RoomNotificationChannelLogic: Symbol.for("RoomNotificationChannelLogic"),
	RoomChannelLogic: Symbol.for("RoomChannelLogic"),
	RoomCategoryChannelLogic: Symbol.for("RoomCategoryChannelLogic"),
};

export const RouteTypes = {
	SlashCommandRoute: Symbol.for("SlashCommandRoute"),
	MessageReplyRoute: Symbol.for("MessageReplyRoute"),
	ReadyStateRoute: Symbol.for("ReadyStateRoute"),
	ReactionRoute: Symbol.for("ReactionRoute"),
	ActionAddBotRoute: Symbol.for("ActionAddBotRoute"),
	ActionRemoveBotRoute: Symbol.for("ActionRemoveBotRoute"),
	ActionAddUserRoute: Symbol.for("ActionAddUserRoute"),
	ActionRemoveUserRoute: Symbol.for("ActionRemoveUserRoute"),
	ActionAddChannelRoute: Symbol.for("ActionAddChannelRoute"),
	ActionRemoveChannelRoute: Symbol.for("ActionRemoveChannelRoute"),
	VoiceChannelEventRoute: Symbol.for("VoiceChannelEventRoute"),
};

export const SchedulerRepoTypes = {
	ReminderSchedulerRepository: Symbol.for("ReminderSchedulerRepository"),
};

export const HandlerTypes = {
	SlashCommandHandler: Symbol.for("SlashCommandHandler"),
	ReactionHandler: Symbol.for("ReactionHandler"),
	MessageHandler: Symbol.for("MessageHandler"),
	ActionAddBotHandler: Symbol.for("ActionAddBotHandler"),
	ActionRemoveBotHandler: Symbol.for("ActionRemoveBotHandler"),
	ActionAddUserHandler: Symbol.for("ActionAddUserHandler"),
	ActionRemoveUserHandler: Symbol.for("ActionRemoveUserHandler"),
	ActionAddChannelHandler: Symbol.for("ActionAddChannelHandler"),
	ActionRemoveChannelHandler: Symbol.for("ActionRemoveChannelHandler"),
	VoiceChannelEventHandler: Symbol.for("VoiceChannelEventHandler"),
};
