export const PredefinedRolesCommandsConst: {
	PredefinedRolesCommands: {
		predefinedRolesId: number;
		commandCategoryType: number;
		commandType: number;
		isAllow: boolean;
	}[];
} = {
	PredefinedRolesCommands: [
		{
			predefinedRolesId: 1,
			commandCategoryType: 1,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 1,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 1,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 1,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 2,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 2,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 3,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 3,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 3,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 5,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 6,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 7,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 4,
			commandType: 8,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 5,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 5,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 6,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 6,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 6,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 6,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 7,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 7,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 7,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 7,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 7,
			commandType: 5,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 7,
			commandType: 6,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 8,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 8,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 9,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 1,
			commandCategoryType: 9,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 1,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 1,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 1,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 1,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 2,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 2,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 3,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 3,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 3,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 5,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 6,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 7,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 4,
			commandType: 8,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 5,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 5,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 6,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 6,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 6,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 6,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 7,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 7,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 7,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 7,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 7,
			commandType: 5,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 7,
			commandType: 6,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 8,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 8,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 9,
			commandType: 1,
			isAllow: false,
		},
		{
			predefinedRolesId: 2,
			commandCategoryType: 9,
			commandType: 2,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 1,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 1,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 1,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 1,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 2,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 2,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 3,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 3,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 3,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 3,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 4,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 5,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 6,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 7,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 4,
			commandType: 8,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 5,
			commandType: 1,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 5,
			commandType: 2,
			isAllow: true,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 6,
			commandType: 1,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 6,
			commandType: 2,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 6,
			commandType: 3,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 6,
			commandType: 4,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 1,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 2,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 3,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 4,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 5,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 6,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 7,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 7,
			commandType: 8,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 8,
			commandType: 1,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 8,
			commandType: 2,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 9,
			commandType: 1,
			isAllow: false,
		},
		{
			predefinedRolesId: 3,
			commandCategoryType: 9,
			commandType: 2,
			isAllow: false,
		},
	],
};
