export const TranslateConst: {
	characterGroups: { character: string; group: string }[];
	removeCharacters: string[];
	characterMaps: { source: string; target: string }[];
	startWords: { character: string; writingWord: string; readingWord: string }[];
} = {
	characterGroups: [
		{ character: "ア", group: "ア" },
		{ character: "イ", group: "イ" },
		{ character: "ウ", group: "ウ" },
		{ character: "ヴ", group: "ウ" },
		{ character: "エ", group: "エ" },
		{ character: "オ", group: "オ" },
		{ character: "カ", group: "カ" },
		{ character: "ガ", group: "カ" },
		{ character: "キ", group: "キ" },
		{ character: "ギ", group: "キ" },
		{ character: "ク", group: "ク" },
		{ character: "グ", group: "ク" },
		{ character: "ケ", group: "ケ" },
		{ character: "ゲ", group: "ケ" },
		{ character: "コ", group: "コ" },
		{ character: "ゴ", group: "コ" },
		{ character: "サ", group: "サ" },
		{ character: "ザ", group: "サ" },
		{ character: "シ", group: "シ" },
		{ character: "ジ", group: "シ" },
		{ character: "ス", group: "ス" },
		{ character: "ズ", group: "ズ" },
		{ character: "セ", group: "セ" },
		{ character: "ゼ", group: "セ" },
		{ character: "ソ", group: "ソ" },
		{ character: "ゾ", group: "ソ" },
		{ character: "タ", group: "タ" },
		{ character: "ダ", group: "タ" },
		{ character: "チ", group: "チ" },
		{ character: "ヂ", group: "チ" },
		{ character: "ツ", group: "ツ" },
		{ character: "ヅ", group: "ツ" },
		{ character: "テ", group: "テ" },
		{ character: "デ", group: "テ" },
		{ character: "ト", group: "ト" },
		{ character: "ド", group: "ト" },
		{ character: "ナ", group: "ナ" },
		{ character: "ニ", group: "ニ" },
		{ character: "ヌ", group: "ヌ" },
		{ character: "ネ", group: "ネ" },
		{ character: "ノ", group: "ノ" },
		{ character: "ハ", group: "ハ" },
		{ character: "バ", group: "ハ" },
		{ character: "パ", group: "ハ" },
		{ character: "ヒ", group: "ヒ" },
		{ character: "ビ", group: "ヒ" },
		{ character: "ピ", group: "ヒ" },
		{ character: "フ", group: "フ" },
		{ character: "ブ", group: "フ" },
		{ character: "プ", group: "フ" },
		{ character: "ヘ", group: "ヘ" },
		{ character: "ベ", group: "ヘ" },
		{ character: "ぺ", group: "ヘ" },
		{ character: "ホ", group: "ホ" },
		{ character: "ボ", group: "ホ" },
		{ character: "ポ", group: "ホ" },
		{ character: "マ", group: "マ" },
		{ character: "ミ", group: "ミ" },
		{ character: "ム", group: "ム" },
		{ character: "メ", group: "メ" },
		{ character: "モ", group: "モ" },
		{ character: "ヤ", group: "ヤ" },
		{ character: "ユ", group: "ユ" },
		{ character: "ヨ", group: "ヨ" },
		{ character: "ラ", group: "ラ" },
		{ character: "リ", group: "リ" },
		{ character: "ル", group: "ル" },
		{ character: "レ", group: "レ" },
		{ character: "ロ", group: "ロ" },
		{ character: "ワ", group: "ワ" },
		{ character: "ヲ", group: "ヲ" },
		{ character: "ン", group: "ン" },
	],
	removeCharacters: [
		"ァ",
		"ィ",
		"ゥ",
		"ェ",
		"ォ",
		"ャ",
		"ュ",
		"ョ",
		"ッ",
		"ー",
	],
	characterMaps: [
		{ source: "ジ", target: "ヂ" },
		{ source: "ヂ", target: "ジ" },
		{ source: "ヲ", target: "オ" },
		{ source: "オ", target: "ヲ" },
	],
	startWords: [
		{ character: "ア", writingWord: "アーマーガア", readingWord: "アーマーガア" },
		{ character: "イ", writingWord: "イーブイ", readingWord: "イーブイ" },
		{ character: "ウ", writingWord: "アズマオウ", readingWord: "アズマオウ" },
		// { character: "ヴ", writingWord: "", readingWord: "" },
		// { character: "エ", writingWord: "", readingWord: "" },
		{ character: "オ", writingWord: "ケイコウオ", readingWord: "ケイコウオ" },
		{ character: "カ", writingWord: "ゼブライカ", readingWord: "ゼブライカ" },
		{ character: "ガ", writingWord: "エモンガ", readingWord: "エモンガ" },
		{ character: "キ", writingWord: "キリンリキ", readingWord: "キリンリキ" },
		{ character: "ギ", writingWord: "カミツルギ", readingWord: "カミツルギ" },
		{ character: "ク", writingWord: "イワーク", readingWord: "イワーク" },
		{ character: "グ", writingWord: "ケッキング", readingWord: "ケッキング" },
		{ character: "ケ", writingWord: "タマゲタケ", readingWord: "タマゲタケ" },
		{ character: "ゲ", writingWord: "オーロンゲ", readingWord: "オーロンゲ" },
		{ character: "コ", writingWord: "エネコ", readingWord: "エネコ" },
		{ character: "ゴ", writingWord: "サニーゴ", readingWord: "サニーゴ" },
		{ character: "サ", writingWord: "キノガッサ", readingWord: "キノガッサ" },
		{ character: "ザ", writingWord: "レックウザ", readingWord: "レックウザ" },
		{ character: "シ", writingWord: "アゴジムシ", readingWord: "アゴジムシ" },
		{ character: "ジ", writingWord: "アマカジ", readingWord: "アマカジ" },
		{ character: "ス", writingWord: "アノプス", readingWord: "アノプス" },
		{ character: "ズ", writingWord: "カゲボウズ", readingWord: "カゲボウズ" },
		// { character: "セ", writingWord: "", readingWord: "" },
		{ character: "ゼ", writingWord: "イルミーゼ", readingWord: "イルミーゼ" },
		{ character: "ソ", writingWord: "ケムッソ", readingWord: "ケムッソ" },
		{ character: "ゾ", writingWord: "ニョロゾ", readingWord: "ニョロゾ" },
		{ character: "タ", writingWord: "ザマゼンタ", readingWord: "ザマゼンタ" },
		{ character: "ダ", writingWord: "ジャローダ", readingWord: "ジャローダ" },
		{ character: "チ", writingWord: "ジラーチ", readingWord: "ジラーチ" },
		// { character: "ヂ", writingWord: "", readingWord: "" },
		{ character: "ツ", writingWord: "アリゲイツ", readingWord: "アリゲイツ" },
		// { character: "ヅ", writingWord: "ヅ", readingWord: "ツ" },
		{ character: "テ", writingWord: "フラエッテ", readingWord: "フラエッテ" },
        { character: "デ", writingWord: "ジガルデ", readingWord: "ジガルデ" },
		{ character: "ト", writingWord: "アイアント", readingWord: "アイアント" },
		{ character: "ド", writingWord: "エアームド", readingWord: "エアームド" },
		{ character: "ナ", writingWord: "ギラティナ", readingWord: "ギラティナ" },
		{ character: "ニ", writingWord: "ケケンカニ", readingWord: "ケケンカニ" },
		{ character: "ヌ", writingWord: "アシレーヌ", readingWord: "アシレーヌ" },
		{ character: "ネ", writingWord: "デデンネ", readingWord: "デデンネ" },
		{ character: "ノ", writingWord: "ソーナノ", readingWord: "ソーナノ" },
		// { character: "ハ", writingWord: "ハ", readingWord: "ハ" },
		{ character: "バ", writingWord: "メラルバ", readingWord: "メラルバ" },
		{ character: "パ", writingWord: "ケララッパ", readingWord: "ケララッパ" },
		{ character: "ヒ", writingWord: "コアルヒー", readingWord: "コアルヒー" },
		{ character: "ビ", writingWord: "スナヘビ", readingWord: "スナヘビ" },
		{ character: "ピ", writingWord: "スコルピ", readingWord: "スコルピ" },
		{ character: "フ", writingWord: "カプ・テテフ", readingWord: "カプ・テテフ" },
		{ character: "ブ", writingWord: "クラブ", readingWord: "クラブ" },
		{ character: "プ", writingWord: "ギャロップ", readingWord: "ギャロップ" },
		// { character: "ヘ", writingWord: "ヘ", readingWord: "ヘ" },
		{ character: "ベ", writingWord: "フラベベ", readingWord: "フラベベ" },
		// { character: "ぺ", writingWord: "ぺ", readingWord: "ヘ" },
		{ character: "ホ", writingWord: "ホーホー", readingWord: "ホーホー" },
		{ character: "ボ", writingWord: "ツボツボ", readingWord: "ツボツボ" },
		{ character: "ポ", writingWord: "ポッポ", readingWord: "ポッポ" },
		{ character: "マ", writingWord: "アメタマ", readingWord: "アメタマ" },
		{ character: "ミ", writingWord: "シェイミ", readingWord: "シェイミ" },
		{ character: "ム", writingWord: "アグノム", readingWord: "アグノム" },
		{ character: "メ", writingWord: "キャモメ", readingWord: "キャモメ" },
		{ character: "モ", writingWord: "アチャモ", readingWord: "アチャモ" },
		{ character: "ヤ", writingWord: "ファイヤー", readingWord: "ファイヤー" },
		{ character: "ユ", writingWord: "クルマユ", readingWord: "クルマユ" },
		// { character: "ヨ", writingWord: "ヨ", readingWord: "ヨ" },
		{ character: "ラ", writingWord: "サザンドラ", readingWord: "サザンドラ" },
		{ character: "リ", writingWord: "アシマリ", readingWord: "アシマリ" },
		{ character: "ル", writingWord: "アブソル", readingWord: "アブソル" },
		{ character: "レ", writingWord: "カプ・レヒレ", readingWord: "カプ・レヒレ" },
		{ character: "ロ", writingWord: "エネコロロ", readingWord: "エネコロロ" },
		{ character: "ワ", writingWord: "キュワワー", readingWord: "キュワワー" },
		// { character: "ヲ", writingWord: "ヲ", readingWord: "ヲ" },
		// { character: "ン", writingWord: "ン", readingWord: "ン" },
	],
};
