export const TranslateConst: {
	characterGroups: { character: string; group: string }[];
	removeCharacters: string[];
	characterMaps: { source: string; target: string }[];
} = {
	characterGroups: [
		{ character: "ア", group: "ア" },
		{ character: "イ", group: "イ" },
		{ character: "ウ", group: "ウ" },
		{ character: "ヴ", group: "ウ" },
		{ character: "エ", group: "エ" },
		{ character: "オ", group: "オ" },
		{ character: "カ", group: "カ" },
		{ character: "ガ", group: "カ" },
		{ character: "キ", group: "キ" },
		{ character: "ギ", group: "キ" },
		{ character: "ク", group: "ク" },
		{ character: "グ", group: "ク" },
		{ character: "ケ", group: "ケ" },
		{ character: "ゲ", group: "ケ" },
		{ character: "コ", group: "コ" },
		{ character: "ゴ", group: "コ" },
		{ character: "サ", group: "サ" },
		{ character: "ザ", group: "サ" },
		{ character: "シ", group: "シ" },
		{ character: "ジ", group: "シ" },
		{ character: "ス", group: "セ" },
		{ character: "ス", group: "セ" },
		{ character: "セ", group: "セ" },
		{ character: "ゼ", group: "セ" },
		{ character: "ソ", group: "ソ" },
		{ character: "ゾ", group: "ソ" },
		{ character: "タ", group: "タ" },
		{ character: "タ", group: "タ" },
		{ character: "チ", group: "チ" },
		{ character: "ヂ", group: "チ" },
		{ character: "ツ", group: "ツ" },
		{ character: "ヅ", group: "ツ" },
		{ character: "テ", group: "テ" },
		{ character: "デ", group: "テ" },
		{ character: "ト", group: "ト" },
		{ character: "ト", group: "ト" },
		{ character: "ナ", group: "ナ" },
		{ character: "ニ", group: "ニ" },
		{ character: "ヌ", group: "ヌ" },
		{ character: "ネ", group: "ネ" },
		{ character: "ノ", group: "ノ" },
		{ character: "ハ", group: "ハ" },
		{ character: "バ", group: "ハ" },
		{ character: "パ", group: "ハ" },
		{ character: "ヒ", group: "ヒ" },
		{ character: "ビ", group: "ヒ" },
		{ character: "ピ", group: "ヒ" },
		{ character: "フ", group: "フ" },
		{ character: "ブ", group: "フ" },
		{ character: "プ", group: "フ" },
		{ character: "ヘ", group: "ヘ" },
		{ character: "ベ", group: "ヘ" },
		{ character: "ぺ", group: "ヘ" },
		{ character: "ホ", group: "ホ" },
		{ character: "ボ", group: "ホ" },
		{ character: "ポ", group: "ホ" },
		{ character: "マ", group: "マ" },
		{ character: "ミ", group: "ミ" },
		{ character: "ム", group: "ム" },
		{ character: "メ", group: "メ" },
		{ character: "モ", group: "モ" },
		{ character: "ヤ", group: "ヤ" },
		{ character: "ユ", group: "ユ" },
		{ character: "ヨ", group: "ヨ" },
		{ character: "ラ", group: "ラ" },
		{ character: "リ", group: "リ" },
		{ character: "ル", group: "ル" },
		{ character: "レ", group: "レ" },
		{ character: "ロ", group: "ロ" },
		{ character: "ワ", group: "ワ" },
		{ character: "ヲ", group: "ヲ" },
		{ character: "ン", group: "ン" },
	],
	removeCharacters: [
		"ァ",
		"ィ",
		"ゥ",
		"ェ",
		"ォ",
		"ャ",
		"ュ",
		"ョ",
		"ッ",
		"ー",
	],
	characterMaps: [
		{ source: "ジ", target: "ヂ" },
		{ source: "ヂ", target: "ジ" },
		{ source: "ヲ", target: "オ" },
		{ source: "オ", target: "ヲ" },
	],
};
