const sourceLanguages = [
	"AR",
	"CS",
	"DA",
	"DE",
	"EL",
	"EN",
	"ES",
	"ET",
	"ET",
	"FR",
	"ID",
	"IT",
	"JA",
	"KO",
	"LV",
	"NB",
	"NL",
	"PL",
	"SV",
	"TR",
	"UK",
	"ZH",
] as const;
export type sourceLanguage = (typeof sourceLanguages)[number];

const targetLanguages = [
	"AR",
	"CS",
	"DA",
	"DE",
	"EL-GB",
	"EN-GB",
	"EN-US",
	"ES",
	"ET",
	"ET",
	"FI",
	"FR",
	"ID",
	"IT",
	"JA",
	"KO",
	"LV",
	"NB",
	"NL",
	"PL",
	"SV",
	"TR",
	"UK",
	"ZH",
	"ZH",
] as const;
export type targetLanguage = (typeof targetLanguages)[number];

export const TranslateConst: {
	source: { name: string; value: sourceLanguage }[];
	target: { name: string; value: targetLanguage }[];
} = {
	source: [
		{ name: "Arabic", value: "AR" },
		// { name: 'Bulgarian', value: 'BG'},
		{ name: "Czech", value: "CS" },
		{ name: "Danish", value: "DA" },
		{ name: "German", value: "DE" },
		{ name: "Greek", value: "EL" },
		{ name: "English", value: "EN" },
		{ name: "Spanish", value: "ES" },
		{ name: "Estonian", value: "ET" },
		{ name: "Finnish", value: "ET" },
		{ name: "French", value: "FR" },
		// { name: 'Hungarian', value: 'HU'},
		{ name: "Indonesian", value: "ID" },
		{ name: "Italian", value: "IT" },
		{ name: "Japanese", value: "JA" },
		{ name: "Korean", value: "KO" },
		// { name: 'Lithuanian', value: 'LT'},
		{ name: "Latvian", value: "LV" },
		{ name: "Norwegian", value: "NB" },
		{ name: "Dutch", value: "NL" },
		{ name: "Polish", value: "PL" },
		// { name: 'Portuguese', value: 'PT'},
		// { name: 'Romanian', value: 'RO'},
		// { name: 'Russian', value: 'RU'},
		// { name: 'Slovak', value: 'SK'},
		// { name: 'Slovenian', value: 'SL'},
		{ name: "Swedish", value: "SV" },
		{ name: "Turkish", value: "TR" },
		{ name: "Ukrainian", value: "UK" },
		{ name: "Chinese", value: "ZH" },
	],
	target: [
		{ name: "Arabic", value: "AR" },
		// { name: 'Bulgarian', value: 'BG'},
		{ name: "Czech", value: "CS" },
		{ name: "Danish", value: "DA" },
		{ name: "German", value: "DE" },
		{ name: "Greek", value: "EL-GB" },
		{ name: "English (British)", value: "EN-GB" },
		{ name: "English (American)", value: "EN-US" },
		{ name: "Spanish", value: "ES" },
		{ name: "Estonian", value: "ET" },
		{ name: "Finnish", value: "ET" },
		{ name: "French", value: "FI" },
		{ name: "French", value: "FR" },
		// { name: 'Hungarian', value: 'HU'},
		{ name: "Indonesian", value: "ID" },
		{ name: "Italian", value: "IT" },
		{ name: "Japanese", value: "JA" },
		{ name: "Korean", value: "KO" },
		// { name: 'Lithuanian', value: 'LT'},
		{ name: "Latvian", value: "LV" },
		{ name: "Norwegian", value: "NB" },
		{ name: "Dutch", value: "NL" },
		{ name: "Polish", value: "PL" },
		// { name: 'Portuguese (Brazilian)', value: 'PT-BR'},
		// { name: 'Portuguese (all Portuguese variants excluding Brazilian Portuguese)', value: 'PT-PT'},
		// { name: 'Romanian', value: 'RO'},
		// { name: 'Russian', value: 'RU'},
		// { name: 'Slovak', value: 'SK'},
		// { name: 'Slovenian', value: 'SL'},
		{ name: "Swedish", value: "SV" },
		{ name: "Turkish", value: "TR" },
		{ name: "Ukrainian", value: "UK" },
		{ name: "Chinese (simplified)", value: "ZH" },
		{ name: "Chinese (traditional)", value: "ZH" },
	],
};
